name: Maven CI/CD

on:
 push:
    branches: [ master ]
 pull_request:
      branches: [ master ]

jobs:
  build_and_test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.7
    - name: Set up JDK 14
      uses: actions/setup-java@v4.2.1
      with:
        java-version: 18
        distribution: jdk

    - name: Build project with Maven
      run: mvn -B package --file pom.xml
